version: '3.8'

services:
  bootnode:
    build:
      context: .
      dockerfile: Dockerfile.bootnode
    volumes:
      - bootnode_data:/root/bootnode_data
      - bootnode_keys:/root/keys
      - bootnode_peerstore:/root/peerstore
    environment:
      - PUBLIC_IP=49.204.107.251
      - LOGLEVEL=debug
      - NETWORK=testnet
      - EXTERNAL_IP=49.204.107.251
      - EXTERNAL_PORT=50505
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50505/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    network_mode: "host"

volumes:
  bootnode_data:
  bootnode_keys:
  bootnode_peerstore:

networks:
  blockchain_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 