package blockchain

import (
	"blockchain-core/blockchain/gas"
	"bytes"
	"crypto/ecdsa"
	"crypto/sha256"
	"encoding/gob"
	"encoding/hex"
	"fmt"
	"math/big"
	"sort"
	"time"
)

// Add these constants
const (
	DefaultGasPrice = 1000  // Base price for normal transactions
	DefaultGasLimit = 21000 // Base gas for simple transfers
	MaxTotalFee     = 2.0   // Maximum total fee in native tokens

	// Transaction types
	TX_REGULAR          = 0 // Regular transaction
	TX_COINBASE         = 1 // Coinbase transaction (block reward)
	TX_VALIDATOR_REWARD = 2 // Validator reward transaction
	TX_STAKE            = 3 // Staking transaction
	TX_VOTE             = 4 // Voting transaction
)

// Transaction represents a blockchain transaction
type Transaction struct {
	TransactionID string              // Unique ID for the transaction
	Sender        string              // Address of the sender
	Receiver      string              // Address of the receiver
	Amount        float64             // Transaction amount
	Timestamp     int64               // Time of creation
	Nonce         uint64              // Add nonce field
	GasFee        float64             // Gas fee for prioritization (added later)
	Inputs        []TransactionInput  // Inputs referencing previous UTXOs
	Outputs       []TransactionOutput // Outputs generated by this transaction
	TxType        int                 // Transaction type (regular, coinbase, etc.)

	// Gas-related fields
	GasLimit     uint64 // Maximum gas willing to use
	GasPrice     uint64 // Price per unit of gas
	GasUsed      uint64 // Actual gas used (set after execution)
	Priority     int    // Transaction priority level
	MaxFeePerGas uint64 `json:"max_fee_per_gas"`
	Data         []byte // Transaction data
	Signature    string // Add signature field
}

// TransactionInput references a UTXO being spent
type TransactionInput struct {
	TransactionID string
	OutputIndex   int
	Signature     string
}

// TransactionOutput defines a new UTXO created by a transaction
type TransactionOutput struct {
	Receiver     string  // Address of the receiver
	Amount       float64 // Amount of tokens
	ScriptPubKey string  // Script that must be satisfied to spend this output
}

// MultiSigTransaction represents a transaction requiring multiple signatures
type MultiSigTransaction struct {
	Transaction
	Signatures map[string]string // Address -> Signature
}

func NewTransaction(sender, receiver string, amount float64, gasPrice uint64, gasLimit uint64) (*Transaction, error) {
	// Create transaction with gas parameters
	tx := &Transaction{
		TransactionID: "", // Will be set after initialization
		Sender:        sender,
		Receiver:      receiver,
		Amount:        amount,
		Timestamp:     time.Now().Unix(),
		GasLimit:      gasLimit,
		GasPrice:      gasPrice,
		MaxFeePerGas:  gasPrice * 2, // Set max fee to 2x the base gas price
		Priority:      gas.PriorityNormal,
		TxType:        TX_REGULAR,            // Regular transaction type
		Inputs:        []TransactionInput{},  // Will be filled later based on available UTXOs
		Outputs:       []TransactionOutput{}, // Will be filled later
	}

	// Create main output to the receiver
	mainOutput := TransactionOutput{
		Receiver: receiver,
		Amount:   amount,
	}

	// Add the main output
	tx.Outputs = append(tx.Outputs, mainOutput)

	// Calculate total gas fee with proper conversion to tokens
	// First calculate total gas units (gasLimit * gasPrice)
	totalGasUnits := tx.GasLimit * tx.GasPrice
	// Then convert the total gas units to tokens
	tx.GasFee = ConvertGasToTokens(totalGasUnits)

	// Validate gas parameters
	if err := tx.ValidateGas(); err != nil {
		return nil, fmt.Errorf("invalid gas parameters: %w", err)
	}

	// Set the transaction ID
	tx.TransactionID = tx.GenerateTransactionID()

	return tx, nil
}

// GenerateTransactionID generates a unique ID for the transaction
func (tx *Transaction) GenerateTransactionID() string {
	data := fmt.Sprintf("%s%s%f%d%d%d%d",
		tx.Sender,
		tx.Receiver,
		tx.Amount,
		tx.GasPrice,
		tx.GasLimit,
		tx.Priority,
		tx.Timestamp,
	)
	hash := sha256.Sum256([]byte(data))
	return hex.EncodeToString(hash[:])
}

// Hash computes the hash of the transaction data.
func (tx *Transaction) Hash() string {
	data := fmt.Sprintf("%s%s%f%d", tx.Sender, tx.Receiver, tx.Amount, tx.Timestamp)
	hash := sha256.Sum256([]byte(data))
	return hex.EncodeToString(hash[:])
}

// SerializeTransaction serializes a transaction
func SerializeTransaction(tx *Transaction) ([]byte, error) {
	var buffer bytes.Buffer
	encoder := gob.NewEncoder(&buffer)
	err := encoder.Encode(tx)
	if err != nil {
		return nil, err
	}
	return buffer.Bytes(), nil
}

// DeserializeTransaction deserializes a transaction
func DeserializeTransaction(data []byte) (*Transaction, error) {
	var tx Transaction
	decoder := gob.NewDecoder(bytes.NewReader(data))
	err := decoder.Decode(&tx)
	if err != nil {
		return nil, err
	}
	return &tx, nil
}

// Equals compares two transactions for deep equality
func (tx *Transaction) Equals(other *Transaction) bool {
	if tx.TransactionID != other.TransactionID ||
		tx.Sender != other.Sender ||
		tx.Receiver != other.Receiver ||
		tx.Amount != other.Amount ||
		tx.Timestamp != other.Timestamp ||
		tx.GasFee != other.GasFee ||
		tx.Signature != other.Signature {
		return false
	}

	// Compare Inputs
	if len(tx.Inputs) != len(other.Inputs) {
		return false
	}
	for i, input := range tx.Inputs {
		if input != other.Inputs[i] {
			return false
		}
	}

	// Compare Outputs
	if len(tx.Outputs) != len(other.Outputs) {
		return false
	}
	for i, output := range tx.Outputs {
		if output != other.Outputs[i] {
			return false
		}
	}

	return true
}

// AddSignature adds a signature to the transaction
func (tx *MultiSigTransaction) AddSignature(address, signature string) error {
	if _, exists := tx.Signatures[address]; exists {
		return fmt.Errorf("signature from %s already exists", address)
	}
	tx.Signatures[address] = signature
	return nil
}

// ValidateSignatures validates a single-signature transaction.
func (tx *Transaction) ValidateSignatures(wallet interface{}, publicKeyMap map[string]*ecdsa.PublicKey) bool {
	if wallet, ok := wallet.(*Wallet); ok {
		return VerifySignature(wallet.PublicKey, tx.Hash(), tx.Signature)
	}
	return false
}

// Hash computes the hash for a multi-signature transaction.
func (tx *MultiSigTransaction) Hash() string {
	return tx.Transaction.Hash()
}

// ValidateSignatures validates a multi-signature transaction.
func (tx *MultiSigTransaction) ValidateSignatures(wallet interface{}, publicKeyMap map[string]*ecdsa.PublicKey) bool {
	multiSigWallet, ok := wallet.(*MultiSigwWallet)
	if !ok {
		return false
	}

	validSigs := 0
	for owner, signature := range tx.Signatures {
		publicKey, exists := publicKeyMap[owner]
		if !exists || publicKey == nil {
			continue
		}
		if VerifySignature(publicKey, tx.Hash(), signature) {
			validSigs++
		}
	}
	return validSigs >= multiSigWallet.RequiredSigs
}

// SignTransaction signs a transaction using the private key
func SignTransaction(tx *Transaction, privateKey *ecdsa.PrivateKey) (string, error) {
	// Get the transaction hash
	txHash := tx.Hash()

	// Use the existing SignMessage function
	signature, err := SignMessage(privateKey, txHash)
	if err != nil {
		return "", fmt.Errorf("failed to sign transaction: %v", err)
	}

	return signature, nil
}

// Add helper method
func (tx *Transaction) CalculateFee() uint64 {
	return tx.GasPrice * tx.GasUsed
}

// Add method to validate gas parameters
func (tx *Transaction) ValidateGas() error {
	// Check gas limit bounds
	if tx.GasLimit < gas.BaseTxGas || tx.GasLimit > (gas.BaseTxGas*100) {
		return fmt.Errorf("gas limit %d outside allowed range [%d, %d]",
			tx.GasLimit, gas.BaseTxGas, gas.BaseTxGas*100)
	}

	// Check gas price minimum
	if tx.GasPrice < gas.MinGasPrice {
		return fmt.Errorf("gas price %d below minimum %d",
			tx.GasPrice, gas.MinGasPrice)
	}

	// Calculate total fee by converting total gas units to tokens
	totalGasUnits := tx.GasLimit * tx.GasPrice
	totalFee := ConvertGasToTokens(totalGasUnits)

	if totalFee > MaxTotalFee {
		return fmt.Errorf("total fee %.2f tokens exceeds maximum %.2f tokens",
			totalFee, MaxTotalFee)
	}

	return nil
}

// GetData returns the transaction data for gas calculation
func (tx *Transaction) GetData() []byte {
	// Combine relevant transaction fields into a byte slice
	data := fmt.Sprintf("%s%s%f%d%d",
		tx.Sender,
		tx.Receiver,
		tx.Amount,
		tx.GasPrice,
		tx.GasLimit,
	)
	return []byte(data)
}

// VerifySignature verifies the transaction signature
func (tx *Transaction) VerifySignature() bool {
	// Special case for coinbase transactions - they don't need signatures
	if tx.IsCoinbase() || tx.IsValidatorReward() {
		return true
	}

	// Create message hash
	message := fmt.Sprintf("%s%s%f%d%d", tx.Sender, tx.Receiver, tx.Amount, tx.Nonce, tx.Timestamp)
	messageHash := sha256.Sum256([]byte(message))

	// Get public key for sender
	publicKey, err := GetPublicKeyForAddress(tx.Sender)
	if err != nil {
		return false
	}

	// Decode signature
	sigBytes, err := hex.DecodeString(tx.Signature)
	if err != nil {
		return false
	}

	// Split signature into r and s
	r := new(big.Int).SetBytes(sigBytes[:len(sigBytes)/2])
	s := new(big.Int).SetBytes(sigBytes[len(sigBytes)/2:])

	return ecdsa.Verify(publicKey, messageHash[:], r, s)
}

// NewCoinbaseTransaction creates a new coinbase transaction as a block reward
func NewCoinbaseTransaction(minerAddress string, reward float64, blockHeight uint64) *Transaction {
	// Create a special coinbase transaction with no inputs
	tx := &Transaction{
		Sender:    "coinbase",
		Receiver:  minerAddress,
		Amount:    reward,
		Timestamp: time.Now().Unix(),
		GasLimit:  0,                                                   // No gas limit for coinbase
		GasPrice:  0,                                                   // No gas price for coinbase
		GasUsed:   0,                                                   // No gas used for coinbase
		GasFee:    0,                                                   // No gas fee for coinbase
		Priority:  0,                                                   // Special priority for coinbase
		TxType:    TX_COINBASE,                                         // Mark as coinbase transaction
		Inputs:    []TransactionInput{},                                // No inputs for coinbase
		Data:      []byte(fmt.Sprintf("Block Reward %d", blockHeight)), // Include block height in data
	}

	// Generate unique ID for the transaction
	tx.TransactionID = tx.GenerateCoinbaseID(blockHeight)

	// Create outputs for the coinbase transaction
	output := TransactionOutput{
		Receiver: minerAddress,
		Amount:   reward,
	}

	// Add output to transaction
	tx.Outputs = append(tx.Outputs, output)

	return tx
}

// GenerateCoinbaseID generates a unique ID for coinbase transactions
func (tx *Transaction) GenerateCoinbaseID(blockHeight uint64) string {
	// Include the block height to ensure unique coinbase transaction per block
	data := fmt.Sprintf("coinbase-%s-%f-%d-%d",
		tx.Receiver,
		tx.Amount,
		tx.Timestamp,
		blockHeight,
	)
	hash := sha256.Sum256([]byte(data))
	return hex.EncodeToString(hash[:])
}

// IsCoinbase returns true if this transaction is a coinbase transaction
func (tx *Transaction) IsCoinbase() bool {
	return tx.TxType == TX_COINBASE
}

// NewValidatorRewardTransaction creates a new transaction to reward a validator
func NewValidatorRewardTransaction(validatorAddress string, reward float64, blockHeight uint64) *Transaction {
	// Create a special validator reward transaction
	tx := &Transaction{
		Sender:    "system",
		Receiver:  validatorAddress,
		Amount:    reward,
		Timestamp: time.Now().Unix(),
		GasLimit:  0,                                                         // No gas limit for system transactions
		GasPrice:  0,                                                         // No gas price for system transactions
		GasUsed:   0,                                                         // No gas used for system transactions
		GasFee:    0,                                                         // No gas fee for system transactions
		Priority:  0,                                                         // Special priority
		TxType:    TX_VALIDATOR_REWARD,                                       // Mark as validator reward transaction
		Inputs:    []TransactionInput{},                                      // No inputs for system transactions
		Data:      []byte(fmt.Sprintf("Validator Reward %d", blockHeight-1)), // Include previous block height in data
	}

	// Generate unique ID for the transaction
	tx.TransactionID = tx.GenerateValidatorRewardID(blockHeight)

	// Create outputs for the validator reward transaction
	output := TransactionOutput{
		Receiver: validatorAddress,
		Amount:   reward,
	}

	// Add output to transaction
	tx.Outputs = append(tx.Outputs, output)

	return tx
}

// GenerateValidatorRewardID generates a unique ID for validator reward transactions
func (tx *Transaction) GenerateValidatorRewardID(blockHeight uint64) string {
	// Include the block height to ensure unique validator transaction per block
	data := fmt.Sprintf("validator-reward-%s-%f-%d-%d",
		tx.Receiver,
		tx.Amount,
		tx.Timestamp,
		blockHeight,
	)
	hash := sha256.Sum256([]byte(data))
	return hex.EncodeToString(hash[:])
}

// IsValidatorReward returns true if this transaction is a validator reward transaction
func (tx *Transaction) IsValidatorReward() bool {
	return tx.TxType == TX_VALIDATOR_REWARD
}

// AddInput adds a UTXO input to the transaction
func (tx *Transaction) AddInput(txID string, outputIndex int, signature string) {
	input := TransactionInput{
		TransactionID: txID,
		OutputIndex:   outputIndex,
		Signature:     signature,
	}
	tx.Inputs = append(tx.Inputs, input)
}

// AddChangeOutput adds a change output back to the sender if needed
func (tx *Transaction) AddChangeOutput(changeAmount float64) {
	if changeAmount > 0 {
		changeOutput := TransactionOutput{
			Receiver: tx.Sender,
			Amount:   changeAmount,
		}
		tx.Outputs = append(tx.Outputs, changeOutput)
	}
}

// SelectUTXOs selects appropriate UTXOs for the transaction
func (tx *Transaction) SelectUTXOs(utxoPool *UTXOPool) error {
	if utxoPool == nil {
		return fmt.Errorf("UTXO pool is nil")
	}

	// Calculate total amount needed (including gas)
	totalNeeded := tx.Amount + tx.GasFee

	// Get all UTXOs for the sender
	senderUTXOs := utxoPool.GetUTXOsForAddress(tx.Sender)
	if len(senderUTXOs) == 0 {
		return fmt.Errorf("no UTXOs found for sender %s", tx.Sender)
	}

	// Sort UTXOs by amount (largest first) for simple selection strategy
	sort.Slice(senderUTXOs, func(i, j int) bool {
		return senderUTXOs[i].Amount > senderUTXOs[j].Amount
	})

	// Select UTXOs and calculate total input
	var selectedUTXOs []UTXO
	totalInput := 0.0

	for _, utxo := range senderUTXOs {
		if utxo.Spent {
			continue
		}
		selectedUTXOs = append(selectedUTXOs, utxo)
		totalInput += utxo.Amount
		if totalInput >= totalNeeded {
			break
		}
	}

	if totalInput < totalNeeded {
		return fmt.Errorf("insufficient funds: have %.8f, need %.8f", totalInput, totalNeeded)
	}

	// Add selected UTXOs as inputs
	for _, utxo := range selectedUTXOs {
		tx.AddInput(utxo.TransactionID, utxo.OutputIndex, "")
	}

	// Add change output if necessary
	changeAmount := totalInput - totalNeeded
	if changeAmount > 0 {
		tx.AddChangeOutput(changeAmount)
	}

	return nil
}
